name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    env:
      OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}  

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6
    - name: Build
      run: go build ./cmd/cli
    - name: Test
      run: go test -count=2 -race ./... 
